// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCACZUT_dA_DtB-Tw1vJtYlDnNUG0aBL-U',
    appId: '1:525802668882:web:3c4a891eccd2fda2de308b',
    messagingSenderId: '525802668882',
    projectId: 'saathi-8a139',
    authDomain: 'saathi-8a139.firebaseapp.com',
    databaseURL: 'https://saathi-8a139-default-rtdb.firebaseio.com',
    storageBucket: 'saathi-8a139.firebasestorage.app',
    measurementId: 'G-GNENDRE8GK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHsHvQ5MdlqMt2CPqnbVp0iwjc8nnrba8',
    appId: '1:525802668882:android:3b8db9fc52dd6e16de308b',
    messagingSenderId: '525802668882',
    projectId: 'saathi-8a139',
    databaseURL: 'https://saathi-8a139-default-rtdb.firebaseio.com',
    storageBucket: 'saathi-8a139.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy2GMudPu3kqGrnPo_6GLKgKOz3fc9xC0',
    appId: '1:525802668882:ios:0aed902abceee8a1de308b',
    messagingSenderId: '525802668882',
    projectId: 'saathi-8a139',
    databaseURL: 'https://saathi-8a139-default-rtdb.firebaseio.com',
    storageBucket: 'saathi-8a139.firebasestorage.app',
    iosBundleId: 'com.acm.saathi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy2GMudPu3kqGrnPo_6GLKgKOz3fc9xC0',
    appId: '1:525802668882:ios:0aed902abceee8a1de308b',
    messagingSenderId: '525802668882',
    projectId: 'saathi-8a139',
    databaseURL: 'https://saathi-8a139-default-rtdb.firebaseio.com',
    storageBucket: 'saathi-8a139.firebasestorage.app',
    iosBundleId: 'com.acm.saathi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCACZUT_dA_DtB-Tw1vJtYlDnNUG0aBL-U',
    appId: '1:525802668882:web:13eec0f4d7fa8911de308b',
    messagingSenderId: '525802668882',
    projectId: 'saathi-8a139',
    authDomain: 'saathi-8a139.firebaseapp.com',
    databaseURL: 'https://saathi-8a139-default-rtdb.firebaseio.com',
    storageBucket: 'saathi-8a139.firebasestorage.app',
    measurementId: 'G-KQEZ19WS9S',
  );

}